spring.application.name=portfolio-service
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/cryptomind}
spring.datasource.username=${POSTGRES_USER:postgres}
spring.datasource.password=${POSTGRES_PASSWORD:pass1234}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

RECOMMENDATION_BASE_URL=${RECOMMENDATION_BASE_URL:http://localhost:8000}

bot.schedule.ms=${BOT_SCHEDULE_MS:300000}
